apiVersion: config.sdcio.dev/v1alpha1
kind: Config
metadata:
  name: config-a
  namespace: default
  labels:
    config.sdcio.dev/targetName: dev2
    config.sdcio.dev/targetNamespace: default
spec:
  priority: 10
  config:
  - path: /
    value:
      interface:
      - name: "system0"
